# 1) Test split() function

In [2]:
import numpy as np
import matplotlib.pyplot as plt

show = False # Turn it to True if you want to plot input data in a image
# Input data --------------------------------------------
i_matrix = np.array([[0, 1, 0, 0], [0, 0, 1, 0]])
print('Original matrix: \n', i_matrix)
if show:
    plt.matshow(i_matrix)
    plt.title('Original matrix')
    plt.show()

# Function ----------------------------------------------
def split(matrix, depth):
    '''
    matrix: matrix shape(mxn)
    Depth: a number > 1
    '''
    n_tensor = [] # new created tensor
    for i in range(0, depth):
        # Creating the padding zero to compensate for the lost path of the shifted matrix
        r_matrix = len(matrix)
        pad = np.zeros((r_matrix, i))

        # 1: a new matrix is generated by concatenate the cut matrix and zero padding
        # 2: Collecting new matrices into a tensor
        n_tensor.append(np.concatenate((matrix[:, i:], pad), axis=1))
    return np.array(n_tensor)

# Show each lice of tensor after using split() function
print('\n' + '#'*15 + ' Print each slice of tensor after using split function ' + '#'*10)
tensor = split(i_matrix, 4)
for idx, i in enumerate(tensor):
    print(f'\nDepth number {idx+1}:')
    print(i)

Original matrix: 
 [[0 1 0 0]
 [0 0 1 0]]

############### Print each slice of tensor after using split function ##########

Depth number 1:
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]]

Depth number 2:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]]

Depth number 3:
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]]

Depth number 4:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 2) Test yield

In [5]:
import numpy as np
from scipy.io import wavfile
import matplotlib.pyplot as plt

def audio_source(name, window):
    sample_rate, samples = wavfile.read(name)
    begin = 0

    while begin < len(samples):
        end = min(begin + window, len(samples))
        yield samples[begin:end]
        begin = end

    print('len(samples) == end?', len(samples) == end)

# here len(piece) is just for showing each piece
generator = [len(piece) for piece in audio_source('wav/apple_and_lemmon.wav', 7000)]
print(list(generator))

len(samples) == end? True
[7000, 7000, 7000, 7000, 1376]


# 3) Test receiver() function

In [1]:
import numpy as np
from scipy.io import wavfile


def audio_source(name, window):
    sample_rate, samples = wavfile.read(name)
    begin = 0

    while begin < len(samples):
        end = min(begin + window, len(samples))
        yield samples[begin:end]
        begin = end

    print('len(samples) == end?', len(samples) == end)

def min_(data, s=False):
    yield np.min(data)

def max_(data, i=1):
    yield np.max(data)

def length_(data):
    yield len(data)

for data in audio_source('wav/apple_and_lemmon.wav', 7000):
    mi = next(min_(data))
    ma = next(max_(data))
    le = next(length_(data))
    print(f'\nMin: {mi}, max: {ma}, length {le}')


Min: -15045, max: 15733, length 7000

Min: -8768, max: 7947, length 7000

Min: -6330, max: 11097, length 7000

Min: -5881, max: 10405, length 7000

Min: -40, max: 1, length 1376
len(samples) == end? True


# 4) Test ma(), stair() and stra() while wav_to_wavelet() using yield

In [4]:
from utils.tools import stairway, wavelet_to_moving_average, matrix_to_vectors
from sklearn.neighbors import NearestCentroid
import numpy as np
from scipy.io import wavfile
from ssqueezepy import ssq_cwt
import numpy as np
import psutil
import soundfile as sf

# Get wavelet from .wav file
def wav_to_wavelet(path, time_window=0.1):
    '''
    x: segment data (1D shape)
    time_window: time in seconds (s)
    '''
    track = sf.SoundFile(path)
    length = track.frames

    can_seek = track.seekable() # To enable access to a file
    if not can_seek:
        raise ValueError("Not compatible with seeking")

    begin = 0
    sr = track.samplerate # sample rate
    start_frame = sr * begin
    sampling_window = int(time_window*sr)
    
    while begin < length:
        # Read and convert .wav file to wavelet
        track.seek(start_frame)
        audio_section = track.read(sampling_window)
        twx, wx, *_ = ssq_cwt(audio_section)  # use wx
        yield np.abs(wx)

        end = min(begin + sampling_window, length)
        begin = end


def stra(matrix, dis = 5):
    shape = matrix.shape
    x, y = matrix_to_vectors(matrix)
    x_list = np.array(np.arange(np.min(x), np.max(x), dis))
    y_list = np.array(np.arange(np.min(y), np.max(y), dis))
    x_1, y_1 = np.meshgrid(x_list, y_list)   # a grid is created by standard straighten

    x_train = np.array([x_1[:, i] for i in range(x_1.shape[1])]).reshape(-1, ).astype(np.int32)
    y_train = np.array([y_1[:, i] for i in range(y_1.shape[1])]).reshape(-1, )

    y_train = np.concatenate((y_train.reshape(-1, 1), x_train.reshape(-1, 1)), axis=-1)
    if len(np.unique(x_train)) < 2:
        return matrix
    ################################### Train with ML ###################################
    # This standard data ((y_train, x_train), x_train) is trained with a Machine Learning (ML) model(NearestCentroid). 
    # After that, using the machine learning
    # model predict original data ((y, x), y)
    clf = NearestCentroid()
    clf.fit(y_train, x_train)
    x = clf.predict(np.concatenate((y.reshape(-1, 1), x.reshape(-1, 1)), axis=-1))
    return x.reshape(shape)
    
path = 'wav/apple_and_lemmon.wav'
window = 1000 # pooling window in MA function
time_window=0.5
bins = 10 # number of bins in stairway function
dis = 200 # distance between columns in stra function

for idx, wx in enumerate(wav_to_wavelet(path, time_window)):
    ma_hist = stairway(wavelet_to_moving_average(wx, window), bins)
    print(f'Shape of stair segment {idx+1}: {ma_hist.shape}')
    ma_hist_stra = stra(ma_hist, dis = dis)
    print(f'Shape of straight segment {idx+1}: {ma_hist_stra.shape}\n')

    print('')
    print('the percentage of used RAM: ', psutil.virtual_memory().percent)
    print('the percentage of available memory: ', psutil.virtual_memory().available * 100 / psutil.virtual_memory().total)


Shape of stair segment 1: (269, 11001)
Shape of straight segment 1: (269, 11001)

the percentage of used RAM:  51.2
the percentage of available memory:  48.78864563787238
Shape of stair segment 2: (269, 11001)
Shape of straight segment 2: (269, 11001)

the percentage of used RAM:  51.1
the percentage of available memory:  48.85401537853301
Shape of stair segment 3: (269, 11001)
Shape of straight segment 3: (269, 11001)

the percentage of used RAM:  51.2
the percentage of available memory:  48.83380141444681


### **The checking memory function**

In [11]:
from collections import Counter
import linecache
import os
import tracemalloc

def display_top(snapshot, key_type='lineno', limit=3, seg=None):
    snapshot = snapshot.filter_traces((
        tracemalloc.Filter(False, "<frozen importlib._bootstrap>"),
        tracemalloc.Filter(False, "<unknown>"),
    ))
    top_stats = snapshot.statistics(key_type)

    print(f"Top {limit} lines of segment {seg}")
    for index, stat in enumerate(top_stats[:limit], 1):
        frame = stat.traceback[0]
        # replace "/path/to/module/file.py" with "module/file.py"
        filename = os.sep.join(frame.filename.split(os.sep)[-2:])
        print("#%s: %s:%s: %.1f KiB"
              % (index, filename, frame.lineno, stat.size / 1024))
        line = linecache.getline(frame.filename, frame.lineno).strip()
        if line:
            print('    %s' % line)

    other = top_stats[limit:]
    if other:
        size = sum(stat.size for stat in other)
        print("%s other: %.1f KiB" % (len(other), size / 1024))
    total = sum(stat.size for stat in top_stats)
    print("Total allocated size: %.1f KiB" % (total / 1024))

### 4.1) Check python memory after each piece

In [12]:
for idx, wx in enumerate(wav_to_wavelet(path, time_window)):
    tracemalloc.start()
    ma_hist = stairway(wavelet_to_moving_average(wx, window), bins)
    ma_hist_stra = stra(ma_hist, dis = dis)
    print('-'*20 + f'Python memory after seeking the segment {idx+1}'+'-'*20)
    snapshot = tracemalloc.take_snapshot()
    display_top(snapshot, seg=idx+1)

--------------------Python memory after seeking the segment 1--------------------
Top 3 lines of segment 1
#1: utils\tools.py:90: 23119.4 KiB
    return np.array(all_dig)
#2: utils\tools.py:89: 6.4 KiB
    all_dig.append(dig.tolist())
#3: ipykernel\iostream.py:458: 0.1 KiB
    def _schedule_in_thread():
17 other: 0.8 KiB
Total allocated size: 23126.7 KiB
--------------------Python memory after seeking the segment 2--------------------
Top 3 lines of segment 2
#1: _pocketfft\basic.py:31: 68864.1 KiB
    return pfft.c2c(tmp, (axis,), forward, norm, out, workers)
#2: utils\backend.py:38: 25218.8 KiB
    return np.zeros(shape, dtype=dtype)
#3: utils\tools.py:90: 23119.4 KiB
    return np.array(all_dig)
74 other: 12922.8 KiB
Total allocated size: 130125.1 KiB
--------------------Python memory after seeking the segment 3--------------------
Top 3 lines of segment 3
#1: _pocketfft\basic.py:31: 68864.1 KiB
    return pfft.c2c(tmp, (axis,), forward, norm, out, workers)
#2: utils\backend.py:38: 

### 4.2) Check python memory after the last piece

In [13]:
tracemalloc.start()
for idx, wx in enumerate(wav_to_wavelet(path, time_window)):
    ma_hist = stairway(wavelet_to_moving_average(wx, window), bins)
    ma_hist_stra = stra(ma_hist, dis = dis)
    
print('#'*20 + ' Python memory after seeking the last piece '+'#'*20)
snapshot = tracemalloc.take_snapshot()
display_top(snapshot, seg='final')

#################### Python memory after seeking the last piece ####################
Top 3 lines of segment final
#1: utils\tools.py:90: 23119.4 KiB
    return np.array(all_dig)
#2: ipykernel_4180\2816025057.py:32: 12609.5 KiB
    yield np.abs(wx)
#3: lib\selectors.py:315: 288.1 KiB
    r, w, x = select.select(r, w, w, timeout)
150 other: 141.1 KiB
Total allocated size: 36158.1 KiB


In [11]:
assert wx.shape[0] == ma_hist.shape[0], f"The number of rows in matrices must be equated, but they are {wx.shape[0]} and {ma_hist.shape[0]} of wx and ma_hist respectively"
assert wx.shape[0] == ma_hist_stra.shape[0], f"The number of rows in matrices must be equated, but they are {wx.shape[0]} and {ma_hist_stra.shape[0]} of wx and ma_hist_stra respectively"    


the percentage of used RAM:  47.7
the percentage of available memory:  52.320493124237004


https://stackoverflow.com/questions/58944777/pytest-is-there-a-way-to-report-memory-usage-of-a-test