# 1) Test split() function

In [2]:
import numpy as np
import matplotlib.pyplot as plt

show = False # Turn it to True if you want to plot input data in a image
# Input data --------------------------------------------
i_matrix = np.array([[0, 1, 0, 0], [0, 0, 1, 0]])
print('Original matrix: \n', i_matrix)
if show:
    plt.matshow(i_matrix)
    plt.title('Original matrix')
    plt.show()

# Function ----------------------------------------------
def split(matrix, depth):
    '''
    matrix: matrix shape(mxn)
    Depth: a number > 1
    '''
    n_tensor = [] # new created tensor
    for i in range(0, depth):
        # Creating the padding zero to compensate for the lost path of the shifted matrix
        r_matrix = len(matrix)
        pad = np.zeros((r_matrix, i))

        # 1: a new matrix is generated by concatenate the cut matrix and zero padding
        # 2: Collecting new matrices into a tensor
        n_tensor.append(np.concatenate((matrix[:, i:], pad), axis=1))
    return np.array(n_tensor)

# Show each lice of tensor after using split() function
print('\n' + '#'*15 + ' Print each slice of tensor after using split function ' + '#'*10)
tensor = split(i_matrix, 4)
for idx, i in enumerate(tensor):
    print(f'\nDepth number {idx+1}:')
    print(i)

Original matrix: 
 [[0 1 0 0]
 [0 0 1 0]]

############### Print each slice of tensor after using split function ##########

Depth number 1:
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]]

Depth number 2:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]]

Depth number 3:
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]]

Depth number 4:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 2) Test yield

In [5]:
import numpy as np
from scipy.io import wavfile
import matplotlib.pyplot as plt

def audio_source(name, window):
    sample_rate, samples = wavfile.read(name)
    begin = 0

    while begin < len(samples):
        end = min(begin + window, len(samples))
        yield samples[begin:end]
        begin = end

    print('len(samples) == end?', len(samples) == end)

# here len(piece) is just for showing each piece
generator = [len(piece) for piece in audio_source('wav/apple_and_lemmon.wav', 7000)]
print(list(generator))

len(samples) == end? True
[7000, 7000, 7000, 7000, 1376]


# 3) Test receiver() function

In [22]:
from utils.tools import audio_source
import numpy as np

def audio_source(name, window):
    sample_rate, samples = wavfile.read(name)
    begin = 0

    while begin < len(samples):
        end = min(begin + window, len(samples))
        yield samples[begin:end]
        begin = end

    print('len(samples) == end?', len(samples) == end)

def min_(data):
    yield np.min(data)

def max_(data):
    yield np.max(data)

def length_(data):
    yield len(data)

for data in audio_source('wav/apple_and_lemmon.wav', 7000):
    max_e = [i for i in max_(data)]
    min_e = [i for i in min_(data)]
    length_e = [i for i in length_(data)]
    print(f'\nMin: {min_e[0]}, max: {max_e[0]}, length {length_e[0]}')


Min: -15045, max: 15733, length 7000

Min: -8768, max: 7947, length 7000

Min: -6330, max: 11097, length 7000

Min: -5881, max: 10405, length 7000

Min: -40, max: 1, length 1376
len(samples) == end? True
